# Generated by Django 3.2.6 on 2021-12-12 21:43

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicaux', models.CharField(max_length=500)),
                ('Chururgicaux', models.CharField(max_length=500)),
                ('Medications_en_cours', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_de_consultation', models.DateTimeField(default=datetime.datetime(2021, 12, 12, 22, 43, 0, 364348))),
                ('Remarques', models.CharField(max_length=500)),
                ('Prochaine_Rondez_vous', models.DateTimeField(default=datetime.datetime(2021, 12, 12, 22, 43, 0, 364348))),
            ],
        ),
        migrations.CreateModel(
            name='Examen_clinique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('PA', models.FloatField()),
                ('SRO', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('poids', models.FloatField(default=1)),
                ('Taille', models.FloatField(default=1)),
                ('RC', models.IntegerField(default=70)),
                ('Reste_de_examen_clinique', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Examen_phisique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintes', models.CharField(max_length=500)),
                ('Examen_Cinetique', models.CharField(max_length=500)),
                ('Reste_de_examen', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Habitude',
            fields=[
                ('Tabagisme', models.CharField(choices=[('YES', 'OUI'), ('NO', 'NON')], max_length=10)),
                ('Nombre_de_Cigarette_par_jours', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Alcool', models.CharField(choices=[('YES', 'OUI'), ('NO', 'NON')], max_length=10)),
                ('Allergies_medicamenteuses', models.CharField(choices=[('YES', 'OUI'), ('NO', 'NON')], max_length=10)),
                ('Autres', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Nom', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('Date_de_naissance', models.DateField()),
                ('Lieu_de_naissance', models.CharField(max_length=200)),
                ('Profession', models.CharField(max_length=200)),
                ('Adresse', models.CharField(max_length=200)),
                ('Cin', models.IntegerField(primary_key=True, serialize=False)),
                ('Sexe', models.CharField(choices=[('Male', 'Masculine'), ('Female', 'Feminine')], max_length=200)),
                ('Statut_matrimonial', models.CharField(choices=[('célibataire', 'célibataire'), ('mariée', 'mariée'), ('veuve', 'veuve'), ('divorcée', 'divorcée')], max_length=200)),
                ('Telephone', models.IntegerField()),
                ('Explorations', models.CharField(max_length=500)),
                ('Traitement', models.CharField(max_length=500)),
                ('Evolution', models.CharField(max_length=500)),
                ('Antecedentes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Patient', to='app.antecedentes')),
                ('Examen_clinique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Patient', to='app.examen_clinique')),
                ('Examen_phisique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Patient', to='app.examen_phisique')),
                ('Habitude', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Patient', to='app.habitude')),
            ],
        ),
    ]
