# Generated by Django 3.2.6 on 2021-10-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('cin', models.IntegerField()),
                ('statut_matrimonial', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(primary_key=True, serialize=False)),
                ('habitude', models.CharField(max_length=400)),
                ('antecedentes', models.CharField(max_length=400)),
                ('medication_en_cours', models.CharField(max_length=400)),
                ('plaintes', models.CharField(max_length=400)),
                ('reste_de_examen', models.CharField(max_length=400)),
                ('T', models.BooleanField()),
                ('PA', models.BooleanField()),
                ('Slo', models.BooleanField()),
                ('RC', models.BooleanField()),
                ('explorations', models.CharField(max_length=400)),
                ('traitement', models.CharField(max_length=400)),
                ('evolution', models.CharField(max_length=400)),
            ],
        ),
    ]
