# Generated by Django 3.2.6 on 2021-12-12 21:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Antecedentes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Evolution',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Examen_clinique',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Examen_phisique',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Explorations',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Habitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Traitement',
        ),
        migrations.AddField(
            model_name='consultation',
            name='Antecedentes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Consultation', to='app.antecedentes'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Evolution',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Examen_clinique',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Consultation', to='app.examen_clinique'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Examen_phisique',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Consultation', to='app.examen_phisique'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Explorations',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Habitude',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Consultation', to='app.habitude'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Patient',
            field=models.ManyToManyField(related_name='Consultation', to='app.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Traitement',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='Chururgicaux',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='Medications_en_cours',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='Medicaux',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Date_de_consultation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 22, 59, 2, 966495)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Prochaine_Rondez_vous',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 22, 59, 2, 966495)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Remarques',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_phisique',
            name='Examen_Cinetique',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_phisique',
            name='Reste_de_examen',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='examen_phisique',
            name='plaintes',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
