# Generated by Django 3.2.6 on 2021-10-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_habitude_patient_tabagisme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='RC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Slo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='T',
            field=models.BooleanField(default=False),
        ),
    ]
