# Generated by Django 3.2.6 on 2021-12-12 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211212_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='Date_de_consultation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 23, 0, 54, 353697)),
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='Patient',
        ),
        migrations.AddField(
            model_name='consultation',
            name='Patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Consultation', to='app.patient'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Prochaine_Rondez_vous',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 23, 0, 54, 353697)),
        ),
    ]
