# Generated by Django 3.2.6 on 2021-12-26 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211220_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen_clinique',
            old_name='poids',
            new_name='Poids',
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='id',
            field=models.AutoField(default=26122021114, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Date_de_consultation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 1, 32, 14, 676465)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Prochaine_Rondez_vous',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 1, 32, 14, 676465)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.AutoField(default=26122021114, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examen_clinique',
            name='id',
            field=models.AutoField(default=26122021114, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examen_phisique',
            name='id',
            field=models.AutoField(default=26122021114, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='habitude',
            name='id',
            field=models.AutoField(default=26122021114, primary_key=True, serialize=False),
        ),
    ]
