# Generated by Django 3.2.6 on 2021-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211031_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
