# Generated by Django 3.2.6 on 2021-12-12 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211212_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen_phisique',
            old_name='Reste_de_examen',
            new_name='Reste_de_examen_phisique',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Date_de_consultation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 23, 3, 24, 220995)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Prochaine_Rondez_vous',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 23, 3, 24, 220995)),
        ),
    ]
