# Generated by Django 3.2.6 on 2021-12-12 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211212_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='Antecedentes',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='Habitude',
        ),
        migrations.AddField(
            model_name='patient',
            name='Antecedentes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Patient', to='app.antecedentes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Habitude',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Patient', to='app.habitude'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Date_de_consultation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 23, 11, 40, 979453)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Prochaine_Rondez_vous',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 23, 11, 40, 979453)),
        ),
    ]
